### PR TITLE
Add optional styling when adding multiple rows to xslx

### PR DESCRIPTION
**Pull request by chrisdicarlo**
Adds an optional, nullable style parameter to the addRows method to allow applying styles to all the rows in the collection.  Brings parity with the singular addRow method since addRows just defers to it anyway.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by ankurk91** [comment]
@freekmurze any plan to release v3 ? with openspout v4.0

https://github.com/spatie/simple-excel/tree/v3

**Comment by freekmurze** [comment]
I'm hoping that a next release of openspout will have a better way of configuring the options, so we don't have to do the nasty tricks that are now in our v3.

I'm thinking of holding of our v3 for a while, as our v2 is working perfectly.

**Comment by ankurk91** [comment]
Thanks for update, i can wait.

**Pull request merged**
