### PR TITLE
Add support for opensprout v4

### PR DESCRIPTION
**Pull request by jwhulette**
Updated to use OpenSpout V4

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you very much for this. I think the API could be improved a bit

Right now we have this. People should create that nasty options object.

```
use OpenSpout\Reader\XLSX\Options;
 // Available options
 // SHOULD_FORMAT_DATES = false;
 // SHOULD_PRESERVE_EMPTY_ROWS = false;
 // SHOULD_USE_1904_DATES = false;
 $options = new Options();
 $options->FIELD_DELIMITER = ';';
 SimpleExcelReader::createXlsx($pathToFile);
```

I think this would be nicer:

```
SimpelExcelReader::options()
   ->delimiter(';')
   ->formatDates()
   // any option method you want
   -->createXlsx($pathToFile)
```

Are maybe even without the `options()`, so you can chain on any method you like directly:

```
SimpelExcelReader::delimiter(';')
   ->formatDates()
   -->createXlsx($pathToFile)
```

Could you make it work like that?

**Comment by jwhulette** [comment]
I will definitely work on that. Much cleaner.

**Comment by jwhulette** [comment]
I updated the code to use options as a static function. I couldn't figure any other way to have it work.

**Comment by freekmurze** [comment]
Thanks for your work on this! I really want calling `options()` to be optional, and I'll see if I can refactor some of your work soon ! 👍

**Comment by jwhulette** [comment]
I really wanted that too :). I'll see if I can also figure something out.

**Comment by jwhulette** [comment]
Finally had time to update to static calls.

**Comment by jwhulette** [comment]
Did a little code cleanup. Now the function signature create is back to being the only one used.

**Comment by freekmurze** [comment]
Thanks for your work on this. I dislike the use of singletons, but I also don't know a better way of handling this. I'm going to pull this in a separate branch and play a bit with it. 👍

**Pull request merged**
