### PR TITLE
Add new sheet to XLSX with Header-Row

### PR DESCRIPTION
**Pull request by red-freak**
The `processingFirstRow` property of the writer prevents the writer to automatically add a header row an newly created sheets by the underlaying writer. So this PR adds the method to the SimpleWriter and resets the `processingFirstRow`-property.

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add tests for this and add an example to the readme?

**Comment by red-freak** [comment]
@freekmurze there seems to be an issue with your assertMatchesFileSnapshot or I do not get how to use it.

Even if the files are copied, the following code will produce an assertion-error, if used for a xlsx. For a csv it works finde.

```
/** @test */
	public function it_can_write_a_csv_without_a_header2()
	{
		SimpleExcelWriter::create($this->pathToXlsx)
						 ->noHeaderRow()
						 ->addRow([
							 'first_name' => 'John',
							 'last_name' => 'Doe',
						 ])
						 ->addRow([
							 'first_name' => 'Jane',
							 'last_name' => 'Doe',
						 ]);

		$this->assertMatchesFileSnapshot($this->pathToXlsx);
	}
```

**Comment by red-freak** [comment]
I see yopu changed to pest, but still the same
```
it('can write a regular XLSX', function () {
    SimpleExcelWriter::create($this->pathToXlsx)
                     ->addRow([
                         'first_name' => 'John',
                         'last_name' => 'Doe',
                     ])
                     ->addRow([
                         'first_name' => 'Jane',
                         'last_name' => 'Doe',
                     ]);

    assertMatchesFileSnapshot($this->pathToXlsx);
});
```
is not working

**Comment by red-freak** [comment]
@freekmurze wrote a test with the limitations mentioned above (there are in general no tests for xlsx as I can see), wrote an example for the README.md and added comments. Please review again.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
